# Generated by Django 4.1.1 on 2022-09-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_remove_flight_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport'),
            preserve_default=False,
        ),
    ]
