# Generated by Django 4.1.1 on 2022-10-09 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='poster',
            field=models.ManyToManyField(related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
