# Generated by Django 4.1.1 on 2022-10-09 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='poster',
        ),
        migrations.AddField(
            model_name='listing',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
