# Generated by Django 4.1.1 on 2022-10-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='poster',
            new_name='user',
        ),
    ]
