# Generated by Django 4.1.1 on 2022-10-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_watchlist_listing_watchlist_listing'),
    ]

    operations = [
    ]
