# Generated by Django 4.1.1 on 2022-10-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20221009_2024'),
    ]

    operations = [
    ]
