# Generated by Django 4.1.1 on 2022-10-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comment_alter_bid_listing_alter_bid_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='items', to='auctions.listing'),
        ),
    ]
