# Generated by Django 4.1.1 on 2022-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_watchlist_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='weapon', max_length=64),
            preserve_default=False,
        ),
    ]
